name: polcam
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - opencv
  - pyside6
  - qtpy
  - matplotlib
  - pytest
  - pytest-qt
  - pytest-cov
  - tifffile
  - pip
  - pip:
    - polanalyser

